var ccb_resources = [
    {type:'image', src:"ccbResources/ccbParticleStars.png"},
    {type:'ccbi', src:"gameplayscene.ccbi"},
    {type:'image', src:"ccbResources/ccbParticleSnow.png"},
    {type:'image', src:"ccbResources/ccbDefaultImages.png"},
    {type:'ccbi', src:"MainScene.ccbi"},
    {type:'ccbi', src:"Player.ccbi"},
    {type:'image', src:"ccbResources/ccbParticleFire.png"},
    {type:'plist', src:"ccbResources/ccbDefaultImages.plist"},
    {type:'image', src:"ccbResources/ccbParticleSmoke.png"},
    {type:'image', src:"ccbResources/Alarmlys00.png"},
    {type:'image', src:"ccbResources/Alarmlys01.png"},
    {type:'image', src:"ccbResources/BOBwalk0.png"},
    {type:'image', src:"ccbResources/BOBwalk1.png"},
    {type:'image', src:"ccbResources/BOBpunch.png"},
    {type:'image', src:"ccbResources/BOBduck.png"},
    {type:"image", src:"ccbResources/caveterraintest.png"},
    {type:"image", src:"ccbResources/PlaceChar.png"},
    {type:"tmx", src:"test-map.tmx"}
];
